In [1]:
import numpy as np
from cvxpy import *
import cvxopt

In [9]:
c = np.array([[100],[100],[100],[100]]);
n = 4 # Number of potential EV candidate Locations
x = Variable(n,boolean=True)
y = Variable((n,n),boolean=True)
w = np.array([[7],[8],[10],[9]])
#y = Variable((n, n))

d = np.array([[0,9,12,12],[0,0,12,12],[0,0,0,12],[0,0,0,0]])

def avg_dist(var_node,var_edge,dist_matrix,min_budget=200,max_budget=200,threshold_dist=10):
    """ 
    This function returns constraints list for the optimization problem. It returns budget constraint, average distance
    constraint, and node-edge coupling constraints
    
      
    Attributes: 
        var_node (n,) : potential cluster nodes -> binary decision variable defined in cvxpy
        var_edge (nxn): edges b/w the nodes -> binary decision variable defined in cvxpy
        dist_matrix (nxn): numpy array of distances b/w the nodes 
        min_budget (float): minimum EV station installation budget 
        max_budget (float): maximum EV station installation budget
        threshold_dist (float): minimum average distance in the cluster
    """
    
    constraints = []
    tot_sum = 0
    count = 0 
    for i in range(n):
            for j in range(n):
                if i >= j:
                    constraints.append(var_edge[i,j] == 0)
                else:
                    tot_sum += dist_matrix[i,j]*var_edge[i,j]
                    count += var_edge[i,j]
                    constraints.append( ((var_node[i] + var_node[j])/2) - var_edge[i,j] <= 0.5 )
                    constraints.append( ((var_node[i] + var_node[j])/2) - var_edge[i,j] >= 0 )
    constraints.append(tot_sum-threshold_dist*count >= 1)
    constraints.append(c.T@x >= min_budget)
    constraints.append(c.T@x <= max_budget)
    return constraints
        

prob = Problem(Minimize(c.T@x-w.T@x), avg_dist(x,y,d))
prob.solve(solver=GLPK_MI)

181.0

In [10]:
d

array([[ 0,  9, 12, 12],
       [ 0,  0, 12, 12],
       [ 0,  0,  0, 12],
       [ 0,  0,  0,  0]])

In [12]:
x.value

array([0., 0., 1., 1.])

In [13]:
y.value

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [6]:
avg_dist(x,y,d)

[Equality(Expression(AFFINE, NONNEGATIVE, ()), Constant(CONSTANT, ZERO, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Constant(CONSTANT, ZERO, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Constant(CONSTANT, ZERO, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Constant(CONSTANT, ZERO, ())),
 Equality(Expression(AFFINE, NONNEGATIVE, ()), Constant(CONSTANT, ZERO, ())),
 Equality(Expression(AFFINE, NONNEGATIVE, ()), Constant(CONSTANT, ZERO, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Constant(CONSTANT, ZERO, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Constant(CONSTANT, ZERO, ())),
 Equality(Expression(AFFINE, NONNEGATIVE, ()), Constant(CONSTANT, ZERO, ())),
 Equality(Expression(AFFINE, NONNEGATIVE, ()), Constant(CONSTANT, ZERO, ())),
 Equality(Expression(AFFINE, NONNEGATIVE, ()), Constant(CONSTANT, ZERO, ())),
 Inequality(Expression(AFFINE, UNKNOWN, ())),
 Inequality(Constant(CONSTANT, ZERO, ()))

In [6]:
### WITHOUT AVERAGE DISTANCE CONSTRAINT
def optimization_func(u, cost = 100.0):
    """ 
    This function returns the optimal EV Charging Station Locations
      
    Attributes: 
        u (float): 1d numpy array 
        cost (float): Installation cost of each charging station 
    """
    
    n = len(u) 
    c = np.ones(n)*cost
    x = Variable(n,boolean=True)

    prob = Problem(Minimize(c.T@x-w.T@x), [c.T@x >= 300,c.T@x <= 350])
    optimal_value = prob.solve(solver=GLPK_MI)
    
    return x.value, optimal_value

In [7]:
w = np.array([[7],[8],[10],[9]])
optimization_func(w)

(array([0., 1., 1., 1.]), 273.0)